image:
  repo: web3f/mongo-express
  tag: latest

basicauth:
  username: admin
  password: pass

mongodb:
  host: mongodb://username:password@polkadot-mongodb-0.polkadot-mongodb-headless:27017,polkadot-mongodb-1.polkadot-mongodb-headless:27017/otv?replicaSet=rs0

certificate:
  enabled: true

backendPort: 8080

domain: example.com
